### PR TITLE
Redundancy of parameters removed by introducing a Constants class

### PR DESCRIPTION
**Pull request by dwamara**
Each new Gateway implementation will have to have a inner class in the new Constants class and have all the constants (parameters etc) listed there as public static final String variables

### CODE REVIEW

**Comment by ilyas2016** [comment]
Hey defining constant class is not a good idea its creating complexity for new comer who would like to integrate new gateway Also there is an idea to implement more than 100 gateways and for that constant class will be a pain.

Yes but we can discus about XML creation.

**Comment by dwamara** [comment]
You can view an example of what happens with using Freemarker for creating the requests, I have already pushed them in the pull request.
Regarding the constants class, it is not the main goal to offer people a solution that works, the quality of the work and the code in this case has to be as good as possible and with the way it was before, the quality wasn’t that good, believe my 20+ years of using Java.
If you want to work on the quality of the code and gain tips that will become intrinsic to your way of working, I will suggest that you use a solution like Sonarqube to check the quality of your code.




Sent with Unibox

**Comment by ilyas2016** [comment]
I can understand but defining constants for just one time use is not a good idea.

**Comment by shanmarif** [comment]
@ilyas2016 @tousifhasanzai I agree with @dwamara its a good approach to use constants although it will create difficulties in Integrations but still we have to meet coding standards as well, if we do not use constants and directly bind parameters/property to a class in the future for any property level change it will be necessary to modify the class which can increase chances of mistakes aka Human Error

**Comment by dwamara** [comment]
The constants is just an approach to get things in the right direction. I don’t pretend on having the all knowing Graal on this, so if you can suggest a better approach, I’m glad to hear and abide by it and will make the necessary modifications to the code that I have written so far for this project.




Sent with Unibox

**Comment by lukkystunt** [comment]
@ilyas2016 @tousifhasanzai i agree with @dwamara having a constant class helps the code base much easier to refactor and also this is the best time to define the coding standard for the project since its relatively still new.

To add more to what @dwamara refactored, i think it would be much better to move all the payment gateways to a separate package, with this you can have more of a schematic structure for each gateway and in the future we can create a script that auto generate schematic structure for new gateways.
examples
```
-----package com.tranxactive.j2pay
            .gateways
                 .billprogateway
                       ---Constant.java
                       ---BillproGateway.java
-----package com.tranxactive.j2pay
            .gateways
                 .authorizegateway
                       ---Constant.java
                       ---AuthorizeGateway.java
```

The above structure makes the code more modular and easier to maintain and enforce coding standards.

**Comment by tousifhasanzai** [comment]
@dwamara what do you think about @lukkystunt review?

**Comment by dwamara** [comment]
That seems OK, but for the package name under "gateways", you can remove "gateway" at the end because as it is supposed to be a gateway, there is no need to repeat it again. And as there will be more than one constant value in the class, the class name has to be in plural form.
If it's ok, I can make the change and let it pass through sonarqube again to be sure that the quality hasn't been affected.
And as @lukkystunt said, that will be a good time to create and enforce standards now. Those standards can be in the future integrated with a solution like checkstyle to be sure that no one is pushing code that doesn't conform to the standards.

**Comment by dwamara** [comment]
But some packages have also to be moved like "com.tranxactive.j2pay.gateways.responses", "com.tranxactive.j2pay.gateways.util". The classes under "com.tranxactive.j2pay.net" are util classes and could be relocated under a more convenient package.

**Comment by ilyas2016** [comment]
yes @dwamara I we can go for it.

**Comment by tousifhasanzai** [comment]
great recommendation @dwamara and @lukkystunt , I am agree with that approach as well

**Comment by dwamara** [comment]
I have just made the changes with the relocation of the classes under a new package with a single Constants class per Gateway and the quality looks like this: https://www.dropbox.com/s/cvg70swubf5q8k2/Screenshot%202018-05-10%2015.26.19.png?dl=0

**Comment by dwamara** [comment]
Made some other changes and now I am at 
screenshot 2018-05-10 15 40 41

**Comment by dwamara** [comment]
I will push that and go out, it's a bank holiday in Germany so I want to enjoy it.

**Comment by ilyas2016** [comment]
image

**Comment by ilyas2016** [comment]
if its failed? then why we implement that?

**Comment by dwamara** [comment]
If what failed?




Sent with Unibox

**Comment by dwamara** [comment]
And BTW someone should think about adding Junit tests.

**Comment by ilyas2016** [comment]
image
 your given snapshot says its failed.

**Comment by dwamara** [comment]
It failed to pass the quality gate. It's exactly what I meant yesterday when I wrote that it's not enough to give people a code that works, it's important to give them a code of good quality and on the quality side, the actual code fails to pass the quality threshold because locally I still have 11 vulnerabilities, 14 code smells, 7h code debt, 7.7% duplications spread between 20 code duplications. 
It says nothing to the functionality of the code, just its quality. For the functionalities, you have to have unit tests that have to be run and this part is still missing.
I know most of the coders think that writing code is enough and don't care about writing tests, and I fell sometimes in that category because I do most functional and integration tests of my code and not unit tests but when you want to give people a library that they have to use, in the future surely in productive systems, you have to assure them that your code is working and that enough unit tests have been made.

**Comment by dwamara** [comment]
But it's a great improvement compared to the code I had when I first checked it out because they were something like 75% duplicated code, 4 days of debt, nearly 60 vulnerabilities and a little more than 300 code smells.

**Comment by dwamara** [comment]
Here what my quality gate looks like
screenshot 2018-05-10 18 25 49

**Comment by dwamara** [comment]
Another thing that I will be adding is a logger, but to have as less as dependencies as possible, I will be doing the logging in a file with the java.util.logging.Logger

**Comment by dwamara** [comment]
I haven't found a better solution than to have a single class per Gateway implementation in a single package as proposed by @lukkystunt

**Comment by ilyas2016** [comment]
Alright so your code with "separate packages for each gateway" is ready. can i merge?/

**Comment by dwamara** [comment]
It’s already been pushed since yesterday, you should be able to merge, all the last coding that I made are in the pull request.
>

**Comment by ilyas2016** [comment]
Why some files are .xml while other are .ftl?

**Comment by dwamara** [comment]
Sorry forgot to rename some, I needed to create first XML files to get them validated before turning them to ftl and I forgot some. Renaming and making another pull request
>

**Comment by ilyas2016** [comment]
and also we should not create two inner classes in constants class like RequestParameters and ResponseParameters instead, we should define directly on constants class level. since you are using ResponseParameters.NAME in request parameters thats not making sense to me.

**Comment by dwamara** [comment]
if you want to do it, then you have to prefix the constants with either REQUEST_ or RESPONSE_ in order to be able to differentiate and know which ones are those for the Request and those for the RESPONSE. I made it that way in order to be able in the future to easily create a documentation (either through Javadoc or something else) where one can directly know and see which parameters for example belong to requests and which not.

**Comment by ilyas2016** [comment]
using ResponseParameters.NAME in request not making any sense how will you sort that out?

**Comment by dwamara** [comment]
I don’t quite get your question
>

**Comment by ilyas2016** [comment]
what if request and request have same parameter name? like both have name

**Comment by ilyas2016** [comment]
test payment gateways are little tricky we would not be able to refund a transactions instantly until it is settled. I am wondering how we could create test cases for that.

**Comment by dwamara** [comment]
If you can’t use a remote system for testing your code, you have to resort to using a mock system or mocking the responses you can get from the system for various use cases (success, failure, failure because system is not reachable, failure because credits are missing, etc).
You can research mocking frameworks for Java on the net but you have for example EasyMock or Mockito that are very well know.
So it’s not that tricky after all, you just have to take your time to learn how to mock and mock.
>

**Comment by dwamara** [comment]
And BTW unit tests are supposed to be implemented to work offline, so they shouldn't rely on external systems, be it a database or something else. As soon as you start using external systems, you move concept wise from unit tests to integration tests.

**Comment by ilyas2016** [comment]
@dwamara please stop any further work. Now library seem more complicated to use or implement new gateways. I will let you when we will decide for changing core of library. thanks.

**Pull request merged**
