### PR TITLE
various cleaning and removal of duplicated codes

### PR DESCRIPTION
**Pull request by dwamara**
- Duplicated codes were removed by introducing new classes
- One-liners on certain code parts are created
- .gitignore more thorough

### CODE REVIEW

**Comment by ilyas2016** [comment]
Hey thats great help.
but you should move the util package to root i.e com.tranxactive.j2pay

**Comment by dwamara** [comment]
The util package has to be with the codes that it changes, but it's your code, so I'll do it as soon as I make new changes to some of the code, there are still improvements to be done. I'll first clean before making improvements to the functionalities.

**Comment by ilyas2016** [comment]
I am also modifying your code a little will submit soon

**Comment by ilyas2016** [comment]
And there is one more thing why TransactionResponse extends VoidResponse it does not make any sense. and leave the util as its now thanks.

**Comment by ilyas2016** [comment]
I am fixing it too.

**Comment by dwamara** [comment]
it doesn't make sense from the name, but looks at the properties that they have, the VoidResponse encapsulates all the properties that the TransactionResponse has, you can make another class that is the exact copy of the VoidResponse and make both VoidResponse and TransactionResponse extend from it, but my philosophy is to have as less classes as I deem possible/necessary

**Comment by ilyas2016** [comment]
Yes i can understand that but i think code must me more readable.
Also please provide your linked in link i would like to add you in special thanks section.

**Comment by dwamara** [comment]
http://linkedin.com/in/danielwamara/

**Comment by ilyas2016** [comment]
thanks and really great work i really appreciate your efforts.

**Comment by ilyas2016** [comment]
thanks bro i have added you profile in special thanks on readme.md

**Comment by dwamara** [comment]
With your last commits, you increased the duplications that I got down to 11% to 75%, this has a great impact on the code quality. See https://imgur.com/a/a1amdug

**Pull request merged**
